version: 2

jobs:
  build:
    working_directory: /go/src/github.com/mije/foobar
    docker:
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: foobar
    steps:
      - checkout
      - run:
          name: Pull dependencies
          command: go get -v -t -d ./...
      - run:
          name: Wait for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          environment:
              DB_URL: "postgres://rot@localhost:5432/foobar?sslmode=disable"
          command: go test -v ./...
